[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "system_trading"
version = "0.1"

dependencies = [
  "yfinance",
  "pandas",
  "matplotlib"
]

readme = "README.md"
